### ISSUE TITLE
User profile endpoint

### ISSUE THREAD

**Issue by 0181532686cf4a31163be0bf3e6bb6732bf** [IonosatMicro/promis#116]
For correct login/logout/userinfo cycle there's need for user profile endpoint which returns 404 or 403 when user is not logged in and username/some other info when it is

**Comment by landswellsong** [comment]
Maybe 401? Also seems to be related with: #49 there is an endpoint already, but it's just not working.

**Comment by 0181532686cf4a31163be0bf3e6bb6732bf** [comment]
https://www.loggly.com/wp-content/uploads/2015/06/http-decision-diagram.png

**Comment by 0181532686cf4a31163be0bf3e6bb6732bf** [comment]
401
