### ISSUE TITLE
Have Cesium auto-repeat the overlay graphics on 2D map

### ISSUE THREAD

**Issue by landswellsong** [IonosatMicro/promis#117]
Have the elements displayed at 0° be repeated at ±360°, ±720° etc etc. This would implicitly solve the polar selection problem as we need to only draw a [(0,-180°); (x; +180°] rectangle and have it repeated if the user decides to scroll horizontally. 

Possibly includes modifying Cesium itself?

**Comment by whokilled** [comment]
Leaflet

**Comment by 0181532686cf4a31163be0bf3e6bb6732bf** [comment]
https://github.com/Leaflet/Leaflet/blob/703ae02aa8cbd0b87be5b01e77754b83ad732267/src/layer/vector/Polygon.js
