### ISSUE TITLE
Docker build for React.js

### ISSUE THREAD

**Issue by landswellsong** [IonosatMicro/promis#120]

**Comment by 0181532686cf4a31163be0bf3e6bb6732bf** [comment]
https://hub.docker.com/r/jmfirth/webpack/
https://medium.com/@andyccs/webpack-and-docker-for-development-and-deployment-ae0e73243db4

**Comment by landswellsong** [comment]
Previt

![image](https://cloud.githubusercontent.com/assets/2434329/25089622/446ffbee-2387-11e7-81b8-9b08b0f63a82.png)
