### ISSUE TITLE
Registration endpoint default group

### ISSUE THREAD

**Issue by 0181532686cf4a31163be0bf3e6bb6732bf** [IonosatMicro/promis#123]
Registering user via `/register` (whatever) endpoint should also add them to specific `level1` or `level2` (probably `level2` since it's default) group to allow actual data fetching

**Comment by landswellsong** [comment]
@lyssdod erm, I don't think so. Users without a group can still get `level2` data, just not the fresh one.

**Comment by 0181532686cf4a31163be0bf3e6bb6732bf** [comment]
@landswellsong whichever group is default should be added. Because without any group user can't even query a list of current projects

**Comment by landswellsong** [comment]
@lyssdod: erm, no I can't confirm. You are mistaking unauthenticated user (also a bug tho) with one that has no group. Proofs:

![image](https://cloud.githubusercontent.com/assets/2434329/25066768/12c007b4-2239-11e7-811a-5617f72bbd20.png)
![image](https://cloud.githubusercontent.com/assets/2434329/25066771/2b59dc78-2239-11e7-9c7f-c426074f6e8d.png)

**Comment by 0181532686cf4a31163be0bf3e6bb6732bf** [comment]
Is `john` just registered user?

**Comment by landswellsong** [comment]
Yep, see `test_set` fixture. 

```
./backend_command loaddata --format json - < test/data/test_set.json
```

**Comment by 0181532686cf4a31163be0bf3e6bb6732bf** [comment]
ok I will check it
