### ISSUE TITLE
Logical description of selection components

### ISSUE THREAD

**Issue by landswellsong** [IonosatMicro/promis#162]
Don't convert rectangles and circles to polygons for the user, just display it intuitively, e.g.:
```
#1: lon range 55-56 lat range 23-40
#2: 400 kms around 55.3123; 123.23
```

**Comment by 0181532686cf4a31163be0bf3e6bb6732bf** [comment]
Rect for 2D, circle for both

**Comment by landswellsong** [comment]
+ add `lon,lat` labels to polygon points editing
