### ISSUE TITLE
Coordinate order in session serializers

### ISSUE THREAD

**Issue by landswellsong** [IonosatMicro/promis#221]
There is a mixup on the order in which geographical coordinates go. Considering φ to be latitude and λ to be longitude, currently (as per upcoming PR tonight) we have the following situation:
- Database stores coordinates as `λ, φ` as per [indication on PostGIS site](http://postgis.net/2013/08/18/tip_lon_lat/)
- API serializer, `orbit.OrbitPoint` and ASCII/CSV exporters all have it `φ, λ ` as per [ISO standard](https://en.wikipedia.org/wiki/ISO_6709)
- Leaflet (2D map) expects `φ, λ `
- Cesium (3D map) doesn't favour anything although the default ordering is `λ, φ`
- Both WKT and GeoJSON expect `λ, φ` . We don't produce either on the backend but we need one or both of them to specify the filter by geographical area when searching for sessions.

Either way we go, we must:
- Clearly indicate the order in the API (e.g. producing objects like `{ lat: 5, lon: 5 }` instead of lists like `[]` in the JSON
- Verify that backend operates in _geographic_ coordinates and not in _projected_ ones.

Bonus: [arguments for `λ, φ`](https://macwright.org/2016/07/15/longitude-latitude-is-the-right-way.html)

**Comment by 0181532686cf4a31163be0bf3e6bb6732bf** [comment]
Cesium and Leaflet maps are fed from internal state object which can store data in any format, so its not a point here

**Comment by landswellsong** [comment]
@lyssdod Leaflet [expects](http://leafletjs.com/reference-1.0.3.html#polyline) data to be in [`LatLng` format](http://leafletjs.com/reference-1.0.3.html#latlng) as far as `Polyline` objects are concerned.

**Comment by 0181532686cf4a31163be0bf3e6bb6732bf** [comment]
All map functions are wrapped, and since Leaflet and Cesium use different formats, conversion will take place in any case. Thus they shouldn't be considered as a valuable factor here.

**Comment by landswellsong** [comment]
@lyssdod currently no preconversion takes place hence my remark. `makeGeolines` of boths takes the same geoline.

**Comment by landswellsong** [comment]
Decided as `φ, λ` as per conversations with @elpiankova @parnowski
