### ISSUE TITLE
3D map can't show a rectangle spanning the day change meridian

### ISSUE THREAD

**Issue by landswellsong** [IonosatMicro/promis#226]
1. Create a rectangle in 2D
2. Switch to 3D
3. See this 
![image](https://cloud.githubusercontent.com/assets/2434329/26055656/70b9be5c-397a-11e7-9e76-0547cfc76ba0.png)

**Comment by 0181532686cf4a31163be0bf3e6bb6732bf** [comment]
Can you post screenshot of rectangle on 2D?

**Comment by landswellsong** [comment]
Draw one from Japan to the US coast.

**Comment by landswellsong** [comment]
![image](https://cloud.githubusercontent.com/assets/2434329/26081673/b88ad40a-39d4-11e7-9414-f7e89564d69a.png)
![image](https://cloud.githubusercontent.com/assets/2434329/26081695/cd4cd910-39d4-11e7-97ca-99829e3a1472.png)

Btw we need to wrap longitudes but that's not an issue right now.
