### ISSUE TITLE
SSL certificate error (NET::ERR_CERT_DATE_INVALID) 

### ISSUE THREAD

**Issue by elpiankova** [IonosatMicro/promis#323]
How we fix it manually from directory /home/elfy/promis:

vagrant halt
sudo certbot renew --standalone
sudo cp -H /etc/letsencrypt/live/promis.ikd.kiev.ua/{fullchain,privkey}.pem ssl/
vagrant up

**Comment by gloriajjl** [comment]
added corresponding script to the server, where promis runs
