### ISSUE TITLE
Project key mismatch

### ISSUE THREAD

**Issue by landswellsong** [IonosatMicro/promis#55]
What's going on here? Isn't `project` the project id? (Same happens for other values, even 1)

![image](https://cloud.githubusercontent.com/assets/2434329/24822403/8ea20a36-1bfd-11e7-8f3b-4c546b1f1ba9.png)

Ok, I got it. The filter is not working yet. UPD: please fix the filter.

**Comment by 0181532686cf4a31163be0bf3e6bb6732bf** [comment]
Possibly use `space_project` instead of `satellite`
